print("ASCII Art of my initials")
print()
print("B B B B   L")
print("B      B  L")
print("B      B  L")
print("B B B B   L")
print("B      B  L")
print("B      B  L")
print("B B B B   L L L L L")
print()

print("ASCII Art of first initial")
print()
print("B B B B")
print("B       B")
print("B       B")
print("B B B B")
print("B       B")
print("B       B")
print("B B B B")
print()

print("ASCII Art of second initial")
print()
print("L")
print("L")
print("L")
print("L")
print("L")
print("L")
print("L L L L L")
print()